### ISSUE TITLE
可以支持直接传入JSON作为数据源吗？

### ISSUE THREAD

**Issue by maxid** [jetlinks/reactor-ql#10]
可以支持直接传入JSON作为数据源吗？

**Comment by zhou-hao** [comment]
可以

**Comment by qingquaner** [comment]
有代码示例吗？mq来了json数据，我该如何处理过滤？

**Comment by zhou-hao** [comment]
> 有代码示例吗？mq来了json数据，我该如何处理过滤？

看看单元测试？ 将mq数据转为Flux<Map>流，传递给ReactorQL就行了。

**Comment by qingquaner** [comment]
特意去学了一下project reactor，要不然还搞不了，呵呵

**Comment by zhou-hao** [comment]
@qingquaner `project reactor` 挺适合数据处理的
