### ISSUE TITLE
纯好奇。和 Flink 的 table SQL 相比，这个的优势在于？

### ISSUE THREAD

**Issue by zgldh** [jetlinks/reactor-ql#2]

**Comment by zhou-hao** [comment]
并不冲突。reactor-ql 超级轻，适合更简单的规则场景，比如纯java内存里的数据运算。而且两者可以结合起来使用。比如 select xxx from flink(select * from flink_table) &nbsp;以及更多的奇淫技巧。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zgldh <notifications@github.com&gt;
发送时间: 2021年1月13日 05:33
收件人: jetlinks/reactor-ql <reactor-ql@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/reactor-ql] 纯好奇。和 Flink 的 table SQL 相比，这个的优势在于？ (#2)

**Comment by zgldh** [comment]
嗯，至少多了一种选择。
