### ISSUE TITLE
group by 支持非列表达式

### ISSUE THREAD

**Issue by sanwanliu** [jetlinks/reactor-ql#5]
Hello，大佬，group by 后续考虑扩展支持非列表达式吗，例如别名或者函数

**Comment by zhou-hao** [comment]
现在是支持函数的。比如 `group by interval('1s')`,实现见https://github.com/jetlinks/reactor-ql/tree/master/src/main/java/org/jetlinks/reactor/ql/supports/group,
想通过列别名的话，需要先进行转换比如:
```sql
select t,count(1)
 from ( select a t from xxx )
 group by t
 ```

**Comment by sanwanliu** [comment]
> 现在是支持函数的。比如 `group by interval('1s')`,实现见https://github.com/jetlinks/reactor-ql/tree/master/src/main/java/org/jetlinks/reactor/ql/supports/group,
> 想通过列别名的话，需要先进行转换比如:
> 
> ```sql
> select t,count(1)
>  from ( select a t from xxx )
>  group by t
> ```

了解了，谢谢
