### ISSUE TITLE
能否实现类似mysql中的substr()功能

### ISSUE THREAD

**Issue by kvj97** [jetlinks/reactor-ql#8]
工作中遇到截取字符串的需求,看了文档和单元测试,好像并没有对应方法

**Comment by zhou-hao** [comment]
已添加`substr`函数 https://github.com/jetlinks/reactor-ql/commit/569202ba7248946b830115fec8469fa39611bb8f

https://github.com/jetlinks/reactor-ql/blob/569202ba7248946b830115fec8469fa39611bb8f/src/test/java/org/jetlinks/reactor/ql/ReactorQLTest.java#L1734-L1752

**Comment by kvj97** [comment]
感谢
